import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#653e00',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-fixed-dim': '#4edea3',
        'surface-container-lowest': '#0c0e16',
        'surface-tint': '#b4c5ff',
        'surface-variant': '#32343d',
        'surface': '#11131b',
        'error-container': '#93000a',
        'surface-container': '#1d1f27',
        'on-secondary-fixed': '#002113',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-container': '#996100',
        'tertiary': '#ffb95f',
        'on-tertiary-container': '#ffeedd',
        'inverse-surface': '#e1e2ed',
        'on-primary-fixed-variant': '#003ea8',
        'on-surface': '#e1e2ed',
        'surface-container-low': '#191b23',
        'surface-container-high': '#282a32',
        'primary-fixed': '#dbe1ff',
        'outline': '#8d90a0',
        'surface-dim': '#11131b',
        'secondary': '#4edea3',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'surface-bright': '#373942',
        'primary-container': '#2563eb',
        'inverse-on-surface': '#2e3039',
        'secondary-container': '#00a572',
        'on-surface-variant': '#c3c6d7',
        'on-background': '#e1e2ed',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary': '#003824',
        'on-tertiary-fixed': '#2a1700',
        'background': '#11131b',
        'on-primary-container': '#eeefff',
        'on-primary': '#002a78',
        'primary': '#b4c5ff',
        'outline-variant': '#434655',
        'tertiary-fixed': '#ffddb8',
        'inverse-primary': '#0053db',
        'on-secondary-container': '#00311f',
        'surface-container-highest': '#32343d',
        'on-tertiary': '#472a00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        gutter: '24px',
        md: '16px',
        base: '4px',
        xs: '4px',
        xl: '48px',
        lg: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'numeric-display': ['Geist', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Geist', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'numeric-display': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
} satisfies Config
